# nav2_params.yaml

amcl:
  ros__parameters:
    use_sim_time: false
    laser_min_range: 0.1
    laser_max_range: 12.0
    laser_scan_topic: "scan"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    map_frame: "map"
    transform_tolerance: 0.2
    update_min_d: 0.2
    update_min_a: 0.2
    min_particle_cloud_size: 500
    max_particle_cloud_size: 2000
    max_beams: 60

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "map.yaml"  # Ścieżka do pliku mapy
    topic: "map"
    frame_id: "map"

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true
      default_tolerance: 0.5

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["DWBLocalPlanner"]

    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.05              # Minimalna prędkość liniowa
      max_vel_x: 0.5             # Maksymalna prędkość liniowa
      min_vel_theta: 0.0          # Minimalna prędkość kątowa
      max_vel_theta: 5          # Maksymalna prędkość kątowa
      acc_lim_x: 0.2              # Ograniczenie przyspieszenia liniowego
      acc_lim_theta: 0.3          # Ograniczenie przyspieszenia kątowego
      min_turning_radius: 0.3     # Minimalny promień skrętu
      vx_samples: 10
      vtheta_samples: 20
      sim_time: 1.5
      discretize_by_time: true
      path_distance_bias: 32.0    # Wpływ odległości od ścieżki
      goal_distance_bias: 24.0    # Wpływ odległości od celu
      occdist_scale: 0.01         # Wpływ odległości od przeszkód

bt_navigator:
  ros__parameters:
    use_sim_time: false
    plugin_lib_names: ["navigate_to_pose_bt_node", "navigate_through_poses_bt_node"]

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    plugin_lib_names: ["waypoint_follower"]

velocity_smoother:
  ros__parameters:
    speed_limit: 0.5  # Ograniczenie prędkości
